# Generated by Django 6.0.3 on 2026-03-05 08:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('hotel_type', models.CharField(max_length=100)),
                ('password', models.CharField(default=0, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phonenumber', models.CharField(validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Normal', 'Normal'), ('2 star', '2 star'), ('5 star', '5 star'), ('delux', 'delux')], default='Normal', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_rooms', models.IntegerField(default=0)),
                ('available_rooms', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='veeduapp.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veeduapp.room')),
            ],
        ),
        migrations.CreateModel(
            name='Hotelbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Normal', 'Normal'), ('2 star', '2 star'), ('5 star', '5 star'), ('delux', 'delux')], default='Normal', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('count', models.IntegerField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('balance_rooms', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hotel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='veeduapp.hotel')),
                ('rooms', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='veeduapp.room')),
                ('assigned_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veeduapp.roomnumber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='veeduapp.user')),
            ],
        ),
    ]
