# Generated by Django 6.0.3 on 2026-03-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veeduapp', '0002_connectionrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectionrequest',
            old_name='callback_url',
            new_name='api_url',
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='website_name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
