# Generated by Django 6.0.3 on 2026-03-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veeduapp', '0003_rename_callback_url_connectionrequest_api_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='website_name',
            field=models.CharField(max_length=100),
        ),
    ]
